### ISSUE TITLE
App crash when choosing plugin

### ISSUE THREAD

**Issue by zwyuan** [mobile-insight/mobileinsight-mobile#16]
Bug: whenever user click the plugin panel from a screen other than the 'HomeScreen', the app will crash.

Version: official release version v3.3.0

Steps to repeat:
1. open MobileInsight app.
2. click 'Settings' button on the upper left
3. click any tab, for example, 'About'
4. click 'Settings' button on the upper left again
5. click 'Plugins'
6. click any plugin, for example, 'NetLogger'

The app will crash with the following adb logcat output:

```
12-05 23:37:13.757  9612  9632 I python  : Traceback (most recent call last):
12-05 23:37:13.757  9612  9632 I python  :   File "/vagrant/mobileinsight-mobile/app/main.py", line 466, in <module>
12-05 23:37:13.757  9612  9632 I python  :   File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/kivy/app.py", line 828, in run
12-05 23:37:13.757  9612  9632 I python  :   File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/kivy/base.py", line 504, in runTouchApp
12-05 23:37:13.757  9612  9632 I python  :   File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 663, in mainloop
12-05 23:37:13.757  9612  9632 I python  :   File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 405, in _mainloop
12-05 23:37:13.757  9612  9632 I python  :   File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/kivy/base.py", line 342, in idle
12-05 23:37:13.757  9612  9632 I python  :   File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/kivy/base.py", line 327, in dispatch_input
12-05 23:37:13.757  9612  9632 I python  :   File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/kivy/base.py", line 293, in post_dispatch_input
12-05 23:37:13.757  9612  9632 I python  :   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8191)
12-05 23:37:13.757  9612  9632 I python  :   File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
12-05 23:37:13.757  9612  9632 I python  :   File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8146)
12-05 23:37:13.757  9612  9632 I python  :   File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy/_event.c:14035)
12-05 23:37:13.757  9612  9632 I python  :   File "kivy/_event.pyx", line 1149, in kivy._event.EventObservers._dispatch (kivy/_event.c:13564)
12-05 23:37:13.757  9612  9632 I python  :   File "/vagrant/mobileinsight-mobile/app/screens/plugins.py", line 116, in callback
12-05 23:37:13.757  9612  9632 I python  :   File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/kivy/uix/screenmanager.py", line 1063, in get_screen
12-05 23:37:13.757  9612  9632 I python  : ScreenManagerException: No Screen with name "HomeScreen".
```

**Comment by yuanjieli** [comment]
Fixed. It is caused by `plugins.py` when the parent screen is not `HomeScreen`.
