### ISSUE TITLE
Support Galaxy S20 FE 5G

### ISSUE THREAD

**Issue by ken32293355** [mobile-insight/mobileinsight-mobile#47]
OS: Android 11
Device::Rooted Galaxy S20 FE 5G
*Build Version: RP1A.200720.012.G781BXXS4CUJ2
Chipset: SM8250

## Description

I very appreciate your work. I try to install mobile insight in Galaxy S20 FE 5G, which has the same chipset as XiaoMi10, SM8250.
However, it will crash after opening the mobile insight app. Could it be fixed? Your app is a great job so that I want to use it for experiment. Thanks a lot.

**Comment by sachinLg** [comment]
Dear All,

I have built the code and generated the APK using the [](https://github.com/mobile-insight/mobileinsight-mobile#quickstart)Quickstart steps mentioned.
The mobileinsight.apk has system uid but whenever I launch the application the app crashes. 

Device used : Samsung Galaxy S20+
MobileInsight: 6.0.0
Chipset: Qualcomm Technologies, Inc KONA
Os: Android 12
 
`I python  :  Traceback (most recent call last):
I python  :    File "/home/vagrant/mi-dev/mobileinsight-mobile/app/main.py", line 5, in <module>
I python  :    File "/home/vagrant/.python-for-android/build/python-installs/MobileInsight/jnius/__init__.py", line 41, in <module>
I python  :  ImportError: dlopen failed: cannot locate symbol "WebView_AndroidGetJNIEnv" referenced by "/data/user/0/net.mobileinsight.app/files/app/_python_bundle/site-packages/jnius/jnius.so"...
I python  : Python for android ended.
I libprocessgroup: Successfully killed process cgroup uid 10287 pid 6277 in 0ms
`

Can you please guide me how to fix this issue.

**Comment by sachinLg** [comment]
Dear All,

I really appreciate your work. 

I have built the code and generated the APK using the [](https://github.com/mobile-insight/mobileinsight-mobile#quickstart)Quickstart steps mentioned.
The mobileinsight.apk has system uid but whenever I launch the application the app crashes. 

Device used : Samsung Galaxy S20+
MobileInsight: 6.0.0
Chipset: Qualcomm Technologies, Inc KONA
Os: Android 12
 
I python  :  Traceback (most recent call last):
I python  :    File "/home/vagrant/mi-dev/mobileinsight-mobile/app/main.py", line 5, in <module>
I python  :    File "/home/vagrant/.python-for-android/build/python-installs/MobileInsight/jnius/__init__.py", line 41, in <module>
I python  :  ImportError: dlopen failed: cannot locate symbol "WebView_AndroidGetJNIEnv" referenced by "/data/user/0/net.mobileinsight.app/files/app/_python_bundle/site-packages/jnius/jnius.so"...
I python  : Python for android ended.
I libprocessgroup: Successfully killed process cgroup uid 10287 pid 6277 in 0ms

Can you please guide me how to fix this issue?
