### ISSUE TITLE
Switch to SDL2 bootstrap

### ISSUE THREAD

**Issue by zwyuan** [mobile-insight/mobileinsight-mobile#5]
Python-for-android is replacing the old `pygame` bootstrap with the newer `SDL2` bootstrap.
We should migrate to SDL2 for richer features and better support.
All the enhancements made for the `pygame` bootstrap (such as broadcasting mechanism) should be migrated to the `SDL2` bootstrap as well.

**Comment by zwyuan** [comment]
The broadcast mechanism does not work right now for the `fix-new-p4a` branch.
For example, when running the RrcAnalysis plugin, the following error pops up:

```
09-29 18:33:07.229 32577 32593 I python2.7:  2017-09-29,18:33:07.229256 [b][color=00ff00][INFO][/color] [LteRrcAnalyzer][/b]: rrc state: RRC_SDRX
09-29 18:33:07.809 32577 32593 I python2.7: killing diag_revealer
09-29 18:33:07.813 32577 32593 I python2.7:  Traceback (most recent call last):
09-29 18:33:07.814 32577 32593 I python2.7:    File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/mobile_insight/monitor/android_dev_diag_monitor.py", line 472, in run
09-29 18:33:07.814 32577 32593 I python2.7:    File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/mobile_insight/element.py", line 108, in send
09-29 18:33:07.814 32577 32593 I python2.7:    File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/mobile_insight/element.py", line 107, in G
09-29 18:33:07.814 32577 32593 I python2.7:    File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/mobile_insight/analyzer/analyzer.py", line 226, in recv
09-29 18:33:07.815 32577 32593 I python2.7:    File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/mobile_insight/analyzer/analyzer.py", line 222, in G
09-29 18:33:07.815 32577 32593 I python2.7:    File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/mobile_insight/analyzer/lte_rrc_analyzer.py", line 249, in __rrc_filter
09-29 18:33:07.815 32577 32593 I python2.7:    File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/mobile_insight/analyzer/lte_rrc_analyzer.py", line 357, in __callback_sib_config
09-29 18:33:07.815 32577 32593 I python2.7:    File "/home/vagrant/.python-for-android/dists/mi3/private/lib/python2.7/site-packages/mobile_insight/element.py", line 254, in broadcast_info
09-29 18:33:07.815 32577 32593 I python2.7:    File "jnius/jnius_export_class.pxi", line 157, in jnius.jnius.JavaClass.__init__ (jnius/jnius.c:19114)
09-29 18:33:07.816 32577 32593 I python2.7:    File "jnius/jnius_export_class.pxi", line 209, in jnius.jnius.JavaClass.call_constructor (jnius/jnius.c:20039)
09-29 18:33:07.816 32577 32593 I python2.7:  JavaException: No constructor matching your arguments
09-29 18:33:07.816 32577 32593 I python2.7:
```

**Comment by zwyuan** [comment]
Merged `fix-new-p4a` into `dev` and `master`. Extensive testing still needed but right now I don't see any problems.
